def hangman(x):
    if (x == 1):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |     ")
        print("    |        ")
        print("    |     ")
        print("  / | \       ")
        print("/   |   \ ")
    elif (x == 2):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |    ○")
        print("    |        ")
        print("    |     ")
        print("  / | \       ")
        print("/   |   \ ")
    elif (x == 3):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |    ○")
        print("    |   ◜◝")
        print("    |   ◟◞")
        print("  / | \       ")
        print("/   |   \ ")
    elif (x == 4):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |    ○")
        print("    |        ")
        print("    |     ")
        print("  / | \       ")
        print("/   |   \ ")
    elif (x == 5):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |    ○")
        print("    |        ")
        print("    |     ")
        print("  / | \       ")
        print("/   |   \ ")
    elif (x == 6):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |    ○")
        print("    |        ")
        print("    |     ")
        print("  / | \       ")
        print("/   |   \ ")
    elif (x == 7):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |    ○")
        print("    |        ")
        print("    |     ")
        print("  / | \       ")
        print("/   |   \ ")
    elif (x == 8):
        print("")
        print("    ————--")
        print("    |    |")
        print("    |    ○")
        print("    |        ")
        print("    |     ")
        print("  / | \       ")
        print("/   |   \ ")
